services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  payment-charges-api:
    build: ./payment-charges-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - WEBHOOK_SECRET=super-secret
      - FLASK_ENV=development
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5000/ready', timeout=3)"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./payment-charges-api/instance:/app/instance
      - ./payment-charges-api/logs:/app/logs
      

  fake-bank-service:
    build: ./fake-bank-service
    restart: unless-stopped
    ports:
      - "6000:6000"
    environment:
      - WEBHOOK_SECRET=super-secret
      - MAX_RETRIES=5
      - INITIAL_DELAY_SECONDS=1
      - BACKOFF_MULTIPLIER=2
      - MAX_DELAY_SECONDS=10
      - TIMEOUT_SECONDS=5
    depends_on:
      payment-charges-api:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:6000/health', timeout=3)"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
